name: dndmin
description: Custom app for custom server management for Dungeons and Dragons sessions.

publish_to: 'none'

version: 0.0.8+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  crypto: ^2.1.5
  flutter_secure_storage: 3.2.1+1
  http: ^0.12.2
  font_awesome_flutter: ^8.8.1
  flutter_launcher_icons: ^0.7.5
  shared_preferences: ^0.5.12+4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/appIcon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: RPGAwesome
      fonts:
        - asset: fonts/RPGAwesome.ttf
    - family: DiceIcons
      fonts:
        - asset: fonts/DiceIcons.ttf